[build]
  publish = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "ALLOW-FROM https://player.vimeo.com"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://player.vimeo.com https://*.vimeocdn.com; img-src 'self' data: https://*.vimeocdn.com https://i.vimeocdn.com; font-src 'self'; frame-src 'self' https://www.youtube.com https://youtube.com https://player.vimeo.com; connect-src 'self' https://vimeo.com https://api.vimeo.com; object-src 'none';"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
